replicaCount: 2
namespace: production
image:
  repository: kunalmane/mern-frontend
  tag: "v15"
ingress:
  enabled: true
  host: todolist.example.com
  path: /
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 60