replicaCount: 2
image:
  repository: 106940013645.dkr.ecr.ap-south-1.amazonaws.com/mern-devsecops-frontend
  tag: "v48"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  host: todolist.kodetechm.com
  path: /
  certificateArn: "arn:aws:acm:ap-south-1:106940013645:certificate/5ef596b8-f5a9-4e47-994c-38bd75d66de0"    # add aws arn acm certificate
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 60
namespace: production
vpa:
  enabled: true
  updateMode: "off"