replicaCount: 2
namespace: production
image:
  repository: 106940013645.dkr.ecr.ap-south-1.amazonaws.com/mern-devsecops-frontend
  tag: "v48"
ingress:
  enabled: true
  host: todolist.kodetechm.com
  path: /
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
<<<<<<< HEAD
  cpuUtilization: 60
=======
  cpuUtilization: 60
vpa:
  enabled: true
  updateMode: "off"
>>>>>>> 2f296f12d9267f34305bad6b883dccb0c32b7a27
