replicaCount: 2
image:
  repository: 696637901454.dkr.ecr.ap-south-1.amazonaws.com/project-frontend
  tag: "v-test-debug"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  host: todolist.kodetechm.com
  path: /
  certificateArn: "arn:aws:acm:ap-south-1:696637901454:certificate/08e7bb56-36e4-4948-8e70-84dcb77bbd2e"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 60
namespace: production
