apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secret.mongoUri }}
  PORT: {{ .Values.secret.port | quote }}
