apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_CONN_STR: {{ .Values.secret.mongoUri | quote }}
  PORT: {{ .Values.secret.port | quote }}
