apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-app-pv
  namespace: {{ .Values.namespace }}
  labels:
    app: mongo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClassName }}
  hostPath:
    path: /data/mongo
    type: DirectoryOrCreate
