apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-app-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
