apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: mongo
spec:
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  serviceName: "mongo-headless"
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
      volumeClaimTemplates:
      - metadata:
          name: mongo-persistent-storage
        spec: 
          accessModes: [ "{{ .Values.storage.accessMode }}" ]
          resources:
            requests:
              storage: {{ .Values.storage.size }}
          storageClassName: {{ .Values.storage.storageClassName }}