apiVersion: v1
kind: Service
metadata:
  name: fe-app
  namespace: {{ .Values.namespace }}
  labels:
    app: fe-app
spec:
  type: {{ .Values.service.Type }}
  selector:
    app: fe-app
  ports:
    - port: {{ .Values.service.Port }}
      targetPort: {{ .Values.service.TargetPort }}
