replicaCount: 2
image:
  repository: 696637901454.dkr.ecr.ap-south-1.amazonaws.com/project-backend
  tag: v14
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5000
  targetPort: 5000
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilization: 60
namespace: production
secretName: backend-secret
configMapName: be-config
secret:
  MONGO_URI: mongodb://mongo:27017/todolist
  port: "5000"
