replicaCount: 2
namespace: production
image: 
  repository: 696637901454.dkr.ecr.ap-south-1.amazonaws.com/project-backend
  tag: "v13"
resources:
  requests:
    cpu: "250m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilization: 60
secretName: backend-secret
configMapName: be-config
secret:
  mongoUri: mongodb://mongo:27017/todolist
  port: "5000"