replicaCount: 2
namespace: production
image:
  tag: "v15"
resources:
  requests:
    cpu: "250m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilization: 60
secretName: backend-secret
configMapName: be-config